version: '2'
services:

  nginx:
    image: nginx:1.13.3-alpine
    ports:
      - "127.0.0.1:9000:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "indices.query.bool.max_clause_count=4096"
      - "cluster.name=sra-metadata-search"
      - "node.name=sra-metadata-search-node1"
      - "discovery.seed_hosts=127.0.0.1, [::1]"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: "65536"
        hard: "65536"
    mem_limit: 6g
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - private

  import:
    build:
      context: ./import/
    entrypoint:
      - tail
      - -f
      - /dev/null
    volumes:
      - ./import:/import:ro
      - ./data:/data:ro
    networks:
      - private

networks:
  public:
    ipam:
      config:
        - subnet: 172.100.99.0/24
  private:
    ipam:
      config:
        - subnet: 172.101.99.0/24
